[fb_console] Fix a release-only build error
Error: "dereferencing type-punned pointer will break strict-aliasing rules"
Caused by the fb_bpp == 24 case in fb_draw_pixel().